### ISSUE TITLE
Software de Comunicação Serial

### ISSUE THREAD

**Issue by gustavobgt** [gustavobgt/home-automation#1]
É preciso criar uma Software de Desktop para comunicação Serial e interface com o Arduino.

**Comment by GabrielSirtoriCorrea** [comment]
Fala Gustavo! Ainda está precisando de um Software de Desktop para o projeto? Se estiver posso ajudá-lo.

**Comment by gustavobgt** [comment]
Opa Gabriel! blz?
Estou sim man, comecei desenvolvendo em C++ e Qt e consegui fazer a comunicação serial com o arduino mas ainda estava com alguns bugs de recpeção principalmente, e ainda irei postar o código. 
Mas pode ser de qualquer linguagem, acho até mais interessante ver várias abordagens para fazer a mesma coisa. 
Se você tiver alguma ideia quero ouvir man!
A ideia por enquanto é basicamente criar uma aplicação gráfica com botões que acionem alguma saída do Arduino quando clicados (para ligar um rele por exemplo), e display para receber sinais analógicos do Arduino (através de sensores de temperatura por exemplo) e mostrar o valor de temperatura nesse display.

**Comment by GabrielSirtoriCorrea** [comment]
Cara minha principal linguagem para desenvolver aplicações gráficas é java. Eu vi que você fez um teste com módulo bluetooth, existem duas opções, se você quiser posso criar um app no android studio para comunicação bluetooth, assim você pode deixar o arduino com os outros componentes em um lugar fixo e controlá-los pelo celular, mas para receber e enviar informações, você precisaria de um módulo mestre-escravo. Já na comunicação serial, eu criaria um software desktop, você conseguiria ter as informações dos sensores, porém terá que ficar com o cabo conectado ao computador

**Comment by gustavobgt** [comment]
Então, eu queria implementar uma comunicação serial via cabo mesmo, com interface gráfica para acompanhar as variáveis (Ex: temperatura, pressão, etc.), e também para acionar saídas do arduino (Ex: reles, leds, etc.).
A questão do app tenho em mente para uma implementação futura.

**Comment by GabrielSirtoriCorrea** [comment]
Se você quiser eu posso te ajudar. É só me passar o nome das variáveis que serão exibidas, ou se você quiser também até passar algumas imagens que você queira colocar na interface

**Comment by gustavobgt** [comment]
No momento tenho interesse em monitorar a temperatura e umidade através do DHT11, e também controlar o acionamento e desligamento de 3 relés através da interface gráfica. Se você puder ajudar ficaria muito grato :). Não tenho nenhuma imagem em particular que desejo colocar, pode ser do seu gosto mesmo.

**Comment by GabrielSirtoriCorrea** [comment]
Blz! Vou ver o que posso fazer!

**Comment by gustavobgt** [comment]
Certo! desde já obrigado man.

**Comment by gustavobgt** [comment]
Opa Gabriel! tranquilo?
Então, eu fiz o passo a passo que você descreveu para conseguir executar o software, mas não consigo abrir o atalho "Arquivo", parece que ele não está conseguindo localizar o diretório.
![image](https://user-images.githubusercontent.com/62708327/83184818-64b6e080-a100-11ea-9679-22871863759e.png)

**Comment by GabrielSirtoriCorrea** [comment]
Ah sim. Eu tentei colocar um atalho pra ficar mais fácil para você. Mas já que não deu certo é só entrar em Interface/InterfaceGraficaAutomacaoResidencial/target Lá vai estar o JAR executável.

**Comment by gustavobgt** [comment]
Opa Gabriel, desculpe a demora para responder. Minha máquina deu um problema e to sem PC por enquanto. Mas antes disso eu dei uma testada com o software e o Arduino e estava funcionando OK! Fiz os procedimentos que você me passou tudo certinho e atualizei o JAVA.

**Comment by GabrielSirtoriCorrea** [comment]
Opa então blz! Fico feliz em ter ajudado!
